// <auto-generated />
namespace CircularManagementSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _22102020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22102020));
        
        string IMigrationMetadata.Id
        {
            get { return "202010220624367_22-10-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
