// <auto-generated />
namespace CircularManagementSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class manymanyupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manymanyupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202012010606444_many-manyupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
